services:
  - type: web
    name: imf-gadget-api
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: imf-gadgets-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: API_RATE_LIMIT
        value: 100

databases:
  - name: imf-gadgets-db
    plan: free
